// flow-typed signature: ac940caaa367a54667f838131d8eefb4
// flow-typed version: <<STUB>>/adjective-animal_v1.1.3/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'adjective-animal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'adjective-animal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'adjective-animal/cli' {
  declare module.exports: any;
}

declare module 'adjective-animal/example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'adjective-animal/cli.js' {
  declare module.exports: $Exports<'adjective-animal/cli'>;
}
declare module 'adjective-animal/example.js' {
  declare module.exports: $Exports<'adjective-animal/example'>;
}
declare module 'adjective-animal/index' {
  declare module.exports: $Exports<'adjective-animal'>;
}
declare module 'adjective-animal/index.js' {
  declare module.exports: $Exports<'adjective-animal'>;
}
