// flow-typed signature: 6cf8cf28fe80117673348904ddd33ff7
// flow-typed version: <<STUB>>/cloudscraper_v1.4.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cloudscraper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cloudscraper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cloudscraper/Gruntfile' {
  declare module.exports: any;
}

declare module 'cloudscraper/specs/chai' {
  declare module.exports: any;
}

declare module 'cloudscraper/specs/spec_helper' {
  declare module.exports: any;
}

declare module 'cloudscraper/specs/tests/cloudscraper' {
  declare module.exports: any;
}

declare module 'cloudscraper/specs/tests/errors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cloudscraper/Gruntfile.js' {
  declare module.exports: $Exports<'cloudscraper/Gruntfile'>;
}
declare module 'cloudscraper/index' {
  declare module.exports: $Exports<'cloudscraper'>;
}
declare module 'cloudscraper/index.js' {
  declare module.exports: $Exports<'cloudscraper'>;
}
declare module 'cloudscraper/specs/chai.js' {
  declare module.exports: $Exports<'cloudscraper/specs/chai'>;
}
declare module 'cloudscraper/specs/spec_helper.js' {
  declare module.exports: $Exports<'cloudscraper/specs/spec_helper'>;
}
declare module 'cloudscraper/specs/tests/cloudscraper.js' {
  declare module.exports: $Exports<'cloudscraper/specs/tests/cloudscraper'>;
}
declare module 'cloudscraper/specs/tests/errors.js' {
  declare module.exports: $Exports<'cloudscraper/specs/tests/errors'>;
}
