// flow-typed signature: 01eaf7a43f4f1bdbf3cfdf02dc3128fe
// flow-typed version: <<STUB>>/countries-list_v2.3.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'countries-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'countries-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'countries-list/dist/index.es5.min' {
  declare module.exports: any;
}

declare module 'countries-list/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'countries-list/dist/index.es5.min.js' {
  declare module.exports: $Exports<'countries-list/dist/index.es5.min'>;
}
declare module 'countries-list/dist/index.js' {
  declare module.exports: $Exports<'countries-list/dist/index'>;
}
