// flow-typed signature: 94d211226f9c8a530ad502b28d786d3c
// flow-typed version: <<STUB>>/duel-names_v1.2.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duel-names'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duel-names' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'duel-names/duel_names' {
  declare module.exports: any;
}

declare module 'duel-names/english' {
  declare module.exports: any;
}

declare module 'duel-names/norwegian' {
  declare module.exports: any;
}

declare module 'duel-names/portuguese' {
  declare module.exports: any;
}

declare module 'duel-names/spanish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'duel-names/duel_names.js' {
  declare module.exports: $Exports<'duel-names/duel_names'>;
}
declare module 'duel-names/english.js' {
  declare module.exports: $Exports<'duel-names/english'>;
}
declare module 'duel-names/norwegian.js' {
  declare module.exports: $Exports<'duel-names/norwegian'>;
}
declare module 'duel-names/portuguese.js' {
  declare module.exports: $Exports<'duel-names/portuguese'>;
}
declare module 'duel-names/spanish.js' {
  declare module.exports: $Exports<'duel-names/spanish'>;
}
