// flow-typed signature: 1b9621b9777f68066a19c3a9e61113d7
// flow-typed version: <<STUB>>/electron-progressbar_v1.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-progressbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-progressbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-progressbar/examples/1-indeterminate-basic/index' {
  declare module.exports: any;
}

declare module 'electron-progressbar/examples/2-determinate-basic/index' {
  declare module.exports: any;
}

declare module 'electron-progressbar/examples/3-custom-style-and-window-options/index' {
  declare module.exports: any;
}

declare module 'electron-progressbar/examples/4-block-parent-window-ui/index' {
  declare module.exports: any;
}

declare module 'electron-progressbar/examples/5-show-progress-bar-on-button-click/index' {
  declare module.exports: any;
}

declare module 'electron-progressbar/source/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-progressbar/examples/1-indeterminate-basic/index.js' {
  declare module.exports: $Exports<'electron-progressbar/examples/1-indeterminate-basic/index'>;
}
declare module 'electron-progressbar/examples/2-determinate-basic/index.js' {
  declare module.exports: $Exports<'electron-progressbar/examples/2-determinate-basic/index'>;
}
declare module 'electron-progressbar/examples/3-custom-style-and-window-options/index.js' {
  declare module.exports: $Exports<'electron-progressbar/examples/3-custom-style-and-window-options/index'>;
}
declare module 'electron-progressbar/examples/4-block-parent-window-ui/index.js' {
  declare module.exports: $Exports<'electron-progressbar/examples/4-block-parent-window-ui/index'>;
}
declare module 'electron-progressbar/examples/5-show-progress-bar-on-button-click/index.js' {
  declare module.exports: $Exports<'electron-progressbar/examples/5-show-progress-bar-on-button-click/index'>;
}
declare module 'electron-progressbar/source/index.js' {
  declare module.exports: $Exports<'electron-progressbar/source/index'>;
}
