// flow-typed signature: 8c1cb2387f4b139a334ad512421a2d1c
// flow-typed version: <<STUB>>/ffa-tb_v1.2.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ffa-tb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ffa-tb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ffa-tb/ffatb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ffa-tb/ffatb.js' {
  declare module.exports: $Exports<'ffa-tb/ffatb'>;
}
