// flow-typed signature: 69f9eb8bb4cdcdd228bf7486753a9c5c
// flow-typed version: <<STUB>>/ffa_v3.2.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ffa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ffa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ffa/ffa_cost' {
  declare module.exports: any;
}

declare module 'ffa/ffa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ffa/ffa_cost.js' {
  declare module.exports: $Exports<'ffa/ffa_cost'>;
}
declare module 'ffa/ffa.js' {
  declare module.exports: $Exports<'ffa/ffa'>;
}
