// flow-typed signature: c387f62dd15a35ca47cf678135ae990e
// flow-typed version: <<STUB>>/groupstage_v3.1.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'groupstage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'groupstage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'groupstage/groupstage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'groupstage/groupstage.js' {
  declare module.exports: $Exports<'groupstage/groupstage'>;
}
