// flow-typed signature: f3c13f2ac336499341fde74e7e6e1f6c
// flow-typed version: <<STUB>>/groupstage-tb-duel_v1.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'groupstage-tb-duel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'groupstage-tb-duel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'groupstage-tb-duel/gstbduel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'groupstage-tb-duel/gstbduel.js' {
  declare module.exports: $Exports<'groupstage-tb-duel/gstbduel'>;
}
