// flow-typed signature: 8836e14fdcb6cc5bc8b2328b67c6b608
// flow-typed version: <<STUB>>/group_v1.0.2/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'group/group' {
  declare module.exports: any;
}

// Filename aliases
declare module 'group/group.js' {
  declare module.exports: $Exports<'group/group'>;
}
