// flow-typed signature: dd33e4b2459169beb78557bc02b19117
// flow-typed version: <<STUB>>/groupstage-tb_v1.3.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'groupstage-tb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'groupstage-tb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'groupstage-tb/gstb' {
  declare module.exports: any;
}

// Filename aliases
declare module 'groupstage-tb/gstb.js' {
  declare module.exports: $Exports<'groupstage-tb/gstb'>;
}
