// flow-typed signature: 2e9c7fb1acf67ad476c2e06fd5c4e05d
// flow-typed version: <<STUB>>/group_v1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'group/group' {
  declare module.exports: any;
}

// Filename aliases
declare module 'group/group.js' {
  declare module.exports: $Exports<'group/group'>;
}
