// flow-typed signature: 98ad07271d69b6327b6c12b9d5a325ef
// flow-typed version: <<STUB>>/informed_v1.5.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'informed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'informed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'informed/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'informed/dist/index.js' {
  declare module.exports: $Exports<'informed/dist/index'>;
}
