// flow-typed signature: 61671a83e2ac17ec31642ca60d2590fc
// flow-typed version: <<STUB>>/masters_v3.1.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'masters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'masters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'masters/ffasub' {
  declare module.exports: any;
}

declare module 'masters/masters' {
  declare module.exports: any;
}

// Filename aliases
declare module 'masters/ffasub.js' {
  declare module.exports: $Exports<'masters/ffasub'>;
}
declare module 'masters/masters.js' {
  declare module.exports: $Exports<'masters/masters'>;
}
