// flow-typed signature: cc818e4020a49f357280637dbeb76178
// flow-typed version: <<STUB>>/react-ratings-declarative_v3.4.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ratings-declarative'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ratings-declarative' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ratings-declarative/__tests__/ratings.test' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/build/ie-isInteger-polyfill' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/build/index' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/build/ratings' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/build/utils' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/build/widget' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/src/ie-isInteger-polyfill' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/src/index' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/src/ratings' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/src/utils' {
  declare module.exports: any;
}

declare module 'react-ratings-declarative/src/widget' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ratings-declarative/__tests__/ratings.test.js' {
  declare module.exports: $Exports<'react-ratings-declarative/__tests__/ratings.test'>;
}
declare module 'react-ratings-declarative/build/ie-isInteger-polyfill.js' {
  declare module.exports: $Exports<'react-ratings-declarative/build/ie-isInteger-polyfill'>;
}
declare module 'react-ratings-declarative/build/index.js' {
  declare module.exports: $Exports<'react-ratings-declarative/build/index'>;
}
declare module 'react-ratings-declarative/build/ratings.js' {
  declare module.exports: $Exports<'react-ratings-declarative/build/ratings'>;
}
declare module 'react-ratings-declarative/build/utils.js' {
  declare module.exports: $Exports<'react-ratings-declarative/build/utils'>;
}
declare module 'react-ratings-declarative/build/widget.js' {
  declare module.exports: $Exports<'react-ratings-declarative/build/widget'>;
}
declare module 'react-ratings-declarative/src/ie-isInteger-polyfill.js' {
  declare module.exports: $Exports<'react-ratings-declarative/src/ie-isInteger-polyfill'>;
}
declare module 'react-ratings-declarative/src/index.js' {
  declare module.exports: $Exports<'react-ratings-declarative/src/index'>;
}
declare module 'react-ratings-declarative/src/ratings.js' {
  declare module.exports: $Exports<'react-ratings-declarative/src/ratings'>;
}
declare module 'react-ratings-declarative/src/utils.js' {
  declare module.exports: $Exports<'react-ratings-declarative/src/utils'>;
}
declare module 'react-ratings-declarative/src/widget.js' {
  declare module.exports: $Exports<'react-ratings-declarative/src/widget'>;
}
