// flow-typed signature: df103bf389cebc83270d7d404f4a17a3
// flow-typed version: <<STUB>>/roundrobin_v1.0.3/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roundrobin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'roundrobin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'roundrobin/robin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'roundrobin/robin.js' {
  declare module.exports: $Exports<'roundrobin/robin'>;
}
