// flow-typed signature: 13ec223568ebffd579f3230c6593eebb
// flow-typed version: <<STUB>>/tiebreaker_v3.1.0/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tiebreaker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tiebreaker' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tiebreaker/tiebreaker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tiebreaker/tiebreaker.js' {
  declare module.exports: $Exports<'tiebreaker/tiebreaker'>;
}
