// flow-typed signature: 2e38094a3e6a5a79d9f19c2c17250d98
// flow-typed version: <<STUB>>/tournament_v3.2.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tournament'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tournament' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tournament/lib/match' {
  declare module.exports: any;
}

declare module 'tournament/lib/tournament' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tournament/lib/match.js' {
  declare module.exports: $Exports<'tournament/lib/match'>;
}
declare module 'tournament/lib/tournament.js' {
  declare module.exports: $Exports<'tournament/lib/tournament'>;
}
