// flow-typed signature: 7db9290746f4cb02694e5ab06df1c819
// flow-typed version: <<STUB>>/tourney_v1.2.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tourney'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tourney' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tourney/tourney' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tourney/tourney.js' {
  declare module.exports: $Exports<'tourney/tourney'>;
}
