/**
 * This allows typescript to pick up the magic constants that are
 * auto-generated by Electron's `contextBridge` interface.
 *
 * @constant
 */
declare const api: typeof import('./lib/api').default;

/**
 * Modal message bus signature.
 *
 * @type {ModalRequest}
 */
declare type ModalRequest<T = unknown> = {
  target: string;
  payload?: T;
};

/** @module */
declare module '*.mp4' {
  const src: string;
  export default src;
}

/** @module */
declare module '*.png' {
  const src: string;
  export default src;
}

/** @module */
declare module '*.webm' {
  const src: string;
  export default src;
}
