const Application = {
  PLAYER_ELIGIBLE_BUFFER_DAYS: 60,
  TEAM_OFFER_RESPONSE_MINDAYS: 1,
  TEAM_OFFER_RESPONSE_MAXDAYS: 2,
  PLAYER_OFFER_RESPONSE_MINDAYS: 1,
  PLAYER_OFFER_RESPONSE_MAXDAYS: 1,

  CALENDAR_LOOP_MAX_ITERATIONS: 5,
  MATCHDAYS_LEAGUE: [ 5, 6, 7 ],        // fri, sat, sun
  MATCHDAYS_LEAGUECUP: [ 1, 2 ],        // mon, tues
  MATCHDAYS_CHAMPLEAGUE: [ 3, 4 ],      // wed, thurs
};


export default Application;
