const Application = {
  PLAYER_ELIGIBLE_BUFFER_DAYS: 60,
  TEAM_OFFER_RESPONSE_MINDAYS: 1,
  TEAM_OFFER_RESPONSE_MAXDAYS: 2,
  PLAYER_OFFER_RESPONSE_MINDAYS: 1,
  PLAYER_OFFER_RESPONSE_MAXDAYS: 1,

  CALENDAR_LOOP_MAX_ITERATIONS: 2,
};


export default Application;
